src/server/mobile/MobileManager.js, src/server/mobile/resources/index.html.ejs
Fixed multi callbacks problem #99
=> Added safe check for android and cordova. Fixes #99

src/server/SocketManager.js, src/server/routes/BasicRoutes.js, src/server/storage/Data.js, src/server/storage/TableStore.js, src/server/tables/ActiveTable.js, src/server/tables/TableManager.js
Restarting the server after adding a seat no longer removes the seats
=> Added better saving support for tables. Fixes #171

src/client/table.js
There is still a problem with the text that needs to be worked out
WIP #200. Added table title box
WIP #200 Fixed the label positioning bug
=> Fixes #200. Added click support

src/client/objects.js, src/server/MessageTypes.js
WIP #249. Added 'message' structure to client
=> Updated available msg types. Fixes #249

src/client/netsblox.js, src/client/room.js, src/server/examples/index.js, src/server/rooms/ActiveRoom.js, src/server/rooms/RoomManager.js, src/server/routes/BasicRoutes.js, src/server/routes/Projects.js, src/server/storage/RoomStore.js
Unfortunately, this also contains some bug fixes from #254
=> Removed `primarySeat`. Fixes #253. Also fixed bugs from #254

src/client/message-inputs.js, src/client/netsblox.js, src/client/room.js, src/client/store.js, src/client/websockets.js, src/server/rooms/ActiveRoom.js, src/server/rooms/NetsBloxSocket.js, src/server/routes/BasicRoutes.js, src/server/storage/RoomStore.js
WIP #297. Exporting/importing rooms now works!
WIP #297. Fixed unique room name
=> Fixes #297. Exporting/importing rooms to xml

src/client/cloud.js, src/client/gui.js, src/client/netsblox.js, src/server/CreateRouter.js, src/server/Server.js, src/server/routes/BasicRoutes.js, src/server/routes/Projects.js, src/server/routes/Rooms.js, src/server/routes/middleware.js, test/server/server.js
Added getURL fix
WIP #339. Updated getURL to check if netsblox error msg
WIP #339
=> Added socketId middleware. Fixes #339

src/client/room.js
WIP #336 Added room morph click listener
=> Added 'click room to leave' as non-owner. Fixes #336

.gitignore, bin/build.js, package.json, src/client/netsblox-dev.html, src/client/netsblox.html
Total time for `DOMContentLoaded` (page load time) went from 2.66 seconds to 589 ms on my development machine. Approximately a 4.5x speedup
=> Added concat, minify build script. Fixes #353

src/server/rpc/RPCManager.js, src/server/rpc/procedures/KVStore/KVStore.js, src/server/rpc/storage.js, src/server/storage/Storage.js
WIP #381
Saving state to db. Fixes #381 
This is required to make the server stateless
=> Saving KeyValueStore state to db. Fixes #381

src/client/netsblox.js, src/server/rpc/libs/earthquakes.xml
`rpc` tagged xml contains blocks and message types
=> Added support for importing `rpc` xml. Fixes #400

src/server/rooms/ActiveRoom.js, src/server/rooms/NetsBloxSocket.js, src/server/routes/Projects.js
Also added more logging. This also fixes an out-of-sync bug wrt roles and sockets.
I suspect this could be causing #366
=> Added join-room from in room detection. Fixes #403

src/server/rpc/procedures/utils/TurnBased.js
WIP #392
WIP #392 Added reset command
=> Added TurnBased utility for RPCs Fixes #392

package.json, src/server/rpc/libs/RPC, src/server/rpc/libs/battleship.xml, src/server/rpc/procedures/Battleship/Battleship.js, src/server/rpc/procedures/Battleship/Board.js, src/server/rpc/procedures/Battleship/Constants.js, test/assets/MockRPC.js, test/server/procedures/battleship.spec.js
WIP #331 Fixed ship length block
WIP #331 Added turns
=> Added Battleship RPC. Fixes #331

src/server/rooms/ActiveRoom.js, src/server/rooms/NetsBloxSocket.js, src/server/routes/Projects.js, src/server/routes/Rooms.js, src/server/storage/RoomStore.js, src/server/storage/UserStore.js
WIP #421. Updating cache on save
WIP #421 Fixed typos
WIP #421 uuid updated. Adding creation timestamp to rooms for id
WIP #421
WIP #421 adding originTime
=> Fixes #421. Added room originTime for comparing same named rooms

src/client/cloud.js, src/server/routes/BasicRoutes.js
WIP #447 Added optional password parameter
=> Changed signup endpoint to 'POST'. Fixes #447

src/server/routes/BasicRoutes.js, src/server/routes/Projects.js, src/server/routes/middleware.js
WIP #418. Added `api/projects/<user>` endpoint
WIP #418 Added viewing other's (public) projects
WIP #418 Added project thumbnail endpoint
WIP #418. Added setUser to getProject
=> Added "list projects" endpoint and thumbnail endpoint. Fixes #418

src/client/cloud.js, src/server/routes/middleware.js
WIP #474
WIP #474
WIP #474 fixed typo
=> Updated login call on reconnect. Fixes #474

src/client/threads.js, src/common/Constants.js, src/server/rpc/procedures/Battleship/Battleship.js, src/server/rpc/procedures/Battleship/Constants.js, src/server/rpc/procedures/EarthQuakes/EarthQuakes.js, src/server/rpc/procedures/TicTacToe/TicTacToe.js, src/server/rpc/procedures/Twenty Questions/Twenty Questions.js
=> Updated rpc url creation. Fixes #506

bin/netsblox.js, package.json
I am not sure if this will fix #498 (I wasn't able to replicate it) but this should help and be good practice anyway
=> Locked the nodemailer version. Closes #498

src/client/websockets.js, src/server/rooms/netsblox-socket.js, src/server/routes/basic-routes.js, src/server/routes/middleware.js, src/server/routes/projects.js, src/server/routes/rooms.js, src/server/rpc/rpc-manager.js, src/server/socket-manager.js, src/server/vantage/vantage.js, test/server/server.js
This is removing some more of the state from the server and should lay some of the groundwork for enhancements like #472
=> Updated websockets to have static uuid. Fixes #855

src/server/rpc/procedures/geolocation/geolocation.js
return null if the api doesn't have a field and the user requests that specific one.
=> change geolocate error handling fixes #1013

src/server/examples/index.js, src/server/rooms/active-room.js, src/server/rooms/netsblox-socket.js, src/server/routes/basic-routes.js, src/server/routes/projects.js, src/server/routes/rooms.js, src/server/server-utils.js, src/server/server.js, src/server/storage/projects.js
This removes the old `cachedProjects` in favor of storing the roles in the database
=> Store the projects directly in the database. Fixes #995

src/server/rpc/rpc-manager.js
guards against losing a handle to old sockets on a new request.
applies only to RPCs made through **ApiConsumer** class to allow for a more relaxed refactoring of old services.
=> separate contexts for services Fixes #1212

src/server/rpc/procedures/british-museum/british-museum.js
tweak a few settings to speedup the searvice,
=> speedup britishmuseum Fixes #1189

src/server/rpc/procedures/movie-db/movie-db.js
=> moviedb sendimage should handle errors  Fixes #1231

bin/netsblox, bin/netsblox-groups-add-member.js, bin/netsblox-groups-list.js, bin/netsblox-groups-new.js, bin/netsblox-groups-rm-member.js, bin/netsblox-groups-rm.js, bin/netsblox-groups.js, src/server/routes/rooms.js, src/server/storage/groups.js, src/server/storage/storage.js, src/server/storage/user-actions.js, src/server/storage/users.js, test/assets/utils.js, test/server/storage/groups.spec.js, test/server/storage/users.spec.js
In the source, these are called "groups"
=> Added sandboxing capabilities for classes. Fixes #801

package.json, test/server/rpc/procedures/eclipse-2017.spec.js, utils/rpc/eclipse-2017/eclipsePath.js
when interpolating eclipse path take the surface of the earth into consideration
=> eclipse path accuracy update, Fixes #1409

src/server/rpc/procedures/eclipse-2017/eclipse-2017.js, test/server/rpc/procedures/eclipse-2017.spec.js, utils/rpc/eclipse-2017/checkStations.js
I believe this kind of the same problem as #1412 but was overlooked before.
=> eclipse dealing with old sensor values in new requests Fixes #1424

src/server/rpc/procedures/dev/dev.js
=> added dev service and echoback rpc Fixes #1448

src/server/rpc/procedures/utils/api-consumer.js, test/server/rpc/procedures/utils/api-consumer.spec.js
=> better caching key Fixes #1478

test/server/rooms/active-room.spec.js
There is still a problem on travis with installing node-canvas but hopefully this will not be a problem after @hamidzr finishes up his work with the new chart service
=> Updated active-room tests. Fixes #1493

package-lock.json, src/server/routes/middleware.js
so that the cookies are accessible to the frontend
=> make cookies accessible to subdomains

src/server/rpc/procedures/dev/dev.js
sending the arguments through the jsonToSnapList was manipulating the arguments when not needed
=> dev/echo should echo raw argument Fixes #1521

src/server/rpc/procedures/geolocation/geolocation.js, test/server/rpc/procedures/geolocation.spec.js
- state
- stateCode
- county
state is actually level  1 administrative area and county is level 2
=> geolocation state / province rpcs Fixes #1565

bin/netsblox, bin/netsblox-analyze-projects.js, bin/netsblox-service-usage.js, src/server/server-utils.js, src/server/storage/projects.js
scans projects for services and prints out [projectName, owner, service]
required for #1514
=> cli tool - scan projects for services Fixes #1494

src/server/rpc/procedures/geolocation/geolocation.js, test/server/rpc/procedures/geolocation.spec.js
a question remains in the issue #1572 
added asterisk to some rpcs
=> adminlevels geolocation Fixes #1572

Dockerfile, Dockerfile.base, README.md, package.json
added netsblox/base Docker image plus an npm command to easily launch docker and develop
=> docker development image #Fixes 1586

src/server/rpc/procedures/twitter/twitter.js
prompted by an issue in how docker parses space in an environment variable
file
=> twitter docker bug Fixes #1587

src/server/rpc/procedures/google-maps/google-maps.js, test/server/rpc/procedures/google-maps.spec.js
calculates distance ( meters )
=> distance rpc for GoogleMaps Fixes #1598

src/client/blocks-ext.js, test/server/build.js
This was breaking the build in production
=> Converted blocks-ext.js to use es5 only. Fixes #1633

src/server/server.js
=> allow CORS * Fixes #1665

src/server/server.js
set allow origin to the requester's origin to make the browser happy
=> CORS with credentials Fixes #1665

src/client/blocks-ext.js
displays help dialog boxes for services block based on the selected service + method from JSDoc blocks
=> auto generated help messages for services Fixes #1696

.gitignore, README.md, src/client/actions.js, src/client/blocks.js, src/client/cloud.js, src/client/gui.js, src/client/netsblox-dev.html, src/client/netsblox.dot, src/client/netsblox.js, src/client/threads.js, src/client/websockets.js, src/server/server.js, test/unit/client/ide.spec.js, test/unit/client/index.html
changes how the server is addressed from the client side so that the client can be served separately from the server (eg, a mobile application)
=> client settable server address Fixes #1667

src/server/rooms/active-room.js, src/server/rooms/netsblox-socket.js, src/server/rooms/room-manager.js, src/server/routes/basic-routes.js, src/server/routes/projects.js, src/server/routes/rooms.js, src/server/storage/projects.js, src/server/vantage/vantage.js, test/unit/server/rooms/active-room.spec.js, test/unit/server/rooms/room-manager.spec.js
This currently hasn't addressed the "active room not found" part of the issue. This may be better suited for a different PR...
=> Updated room-manager to store rooms by project id. Closes #1778

test/unit/client/index.html, test/unit/client/room.spec.js, test/unit/client/snap-driver.js
These have been added under `test/unit/client/` as this currently contains all the client tests but we should move this later as they are not unit tests
=> Added tests for room/role actions testing. Fixes #1795

test/unit/client/actions.spec.js, test/unit/client/index.html
I am fixing this in stable separately since it has a different submodule (containing the same fix though)
=> Updated submodule and added tests for traversing blocks. Fixes #1810

package-lock.json, package.json
Also updated browser code for collab editing fixes
=> Updated snap2js for security updates. Fixes #1850

src/server/routes/middleware.js, src/server/server.js
Although this was motivated by simplifying the client code base, this also helps with #1781
=> Replaced dev html file usage with server side rendering. Closes #1853

README.md, src/server/server.js
the server was misdetecting the protocol because of the Nginx proxy sitting in front
=> configurable server protocol Fixes #1877

src/server/rpc/procedures/iex-trading/iex-trading.js
Added an stock quote rpc using IEXTrading API
=> Adding IEXTrading Service

src/server/rpc/procedures/geolocation/geolocation.js, test/unit/server/rpc/procedures/geolocation.spec.js
added precise caching for `nearbySearch` and `geolocate` RPCs
=> improved caching for geolocation service

test/unit/server/storage/blob/index.spec.js
=> restored server tests Fixes #1869

package.json
increased mocha timeout to (hopefully) prevent TravisCI from timing out
=> longer mocha timeout

package-lock.json, package.json
removed socket.io and its dependencies
=> removed unused package socketio

src/server/rooms/netsblox-socket.js
it is now handled by the server
=> removed request-new-name message handler

src/server/rpc/procedures/iex-trading/iex-trading.js, test/unit/server/rpc/procedures/iex-trading.spec.js
=> Added Historical Close Prices to IEXTrading RPC

src/server/rpc/procedures/geolocation/geolocation.js, src/server/rpc/procedures/movie-db/movie-db.js, src/server/rpc/procedures/roboscape/roboscape.js
I also renamed `movieDB` to upper camelcase to match convention.
=> Use isSupported in geolocation,roboscape,moviedb services. Closes #1961

package-lock.json, package.json, src/server/routes/basic-routes.js
=> Full examples for safari browsers

.codeclimate.yml
increases codeclimate threshold for long files and functions
=> relax codeclimate restrictions

src/server/server.js
This should fix non-deterministic failures in the client tests and simplify communication between the client and server.
=> Generate client ID (socket uuid) server-side Closes #2081

src/server/rooms/netsblox-socket.js, src/server/rooms/room-manager.js, src/server/routes/middleware.js, src/server/routes/projects.js, src/server/routes/rooms.js, src/server/rpc/rpc-manager.js, src/server/server-utils.js, src/server/server.js, src/server/storage/projects.js, test/unit/server/server.js
This removes the websocket connection dependency from the RPC requests. However, other actions such as saving and creating new projects still depend on a websocket connection.
=> Removed websocket dependency from RPCs. Closes #2083

src/server/rpc/procedures/google-maps/google-maps.js
This should improve the reliability of the GoogleMaps service in the presence of a flaky websocket connection (or no websocket connection at all).
=> Removed ws dependency from GoogleMaps. Closes #2128

src/server/rpc/procedures/cloud-variables/cloud-variables.js
This depends on https://github.com/NetsBlox/NetsBlox/pull/2131 (which makes caller info available to the RPC outside of the websocket connection).
=> Updated CloudVariables to use caller instead of ws. Closes #2127

src/server/rpc/procedures/roboscape/firmware/abdrive360.c, src/server/rpc/procedures/roboscape/firmware/abdrive360.h, src/server/rpc/procedures/roboscape/firmware/servo360.c, src/server/rpc/procedures/roboscape/firmware/servo360.h
https://github.com/NetsBlox/NetsBlox/blob/01fe5010f5c081f298a5eb9251b84d333efd20e5/src/server/rpc/procedures/roboscape/firmware/roboscape.c#L1
=> added the missing Roboscape firmware libraries Fixes #2176

src/server/storage/projects.js
This is required by #2165. Well, "required" is a little strong but used anyway :)
=> Support for destroying projects w/o loading. Closes #2194

src/server/rpc/procedures/air-quality/air-quality.js, src/server/rpc/procedures/battleship/battleship.js, src/server/rpc/procedures/british-museum/british-museum.js, src/server/rpc/procedures/earthquakes/earthquakes.js, src/server/rpc/procedures/water-watch/water-watch.js, test/unit/server/rpc/procedures/airquality.spec.js
Small batch to get some of them included sooner.
Adds annotations to:
- air-quality
- battleship
- british-museum
- earthquake
- water-watch
Moved to APIConsumer:
- air-quality (with updated tests)
=> RPC Refactor WIP (#2155)

package.json
=> simplified npm scripts Fixes #2230

src/server/mailer.js
DKIM, SPF, _DMARC, RDNS dns records were also set
=> support for using external SMTP server for outgoing email. Fixes #2254

bin/netsblox, bin/netsblox-export-user-projects.js, src/server/storage/projects.js
=> export all projects of a user fixes #2275 

package-lock.json, package.json
support new js syntax eg `async`
=> update istanbul Fixes #2293

src/server/rpc/procedures/google-maps/google-maps.js
follow the convention to allow jsdoc association (for help generation)
=> fixed help messages for google-maps Fixes #2302

src/server/rpc/jsdoc-extractor.js, test/unit/server/rpc/jsdoc-extractor.spec.js
support `functionName: function()`
=> expanded function finding support for jsdoc-extractor Fixes #2305

.travis.yml, src/server/server.js, test/test.env
resets and seeds the given database in test environment (`ENV=test`)
client tests require a seeded database.
=> reset and seed test database on start

src/server/storage/projects.js, test/unit/server/storage/projects.js
adds some tests for the caching functionality and this new change
=> improve project caching, ignore null values

src/server/rpc/procedures/nasa/nasa.js
the service provider is no longer providing service http://ingenology.github.io/mars_weather_api/
=> deprecated mars rpcs #2301

bin/netsblox-start.js
adds an additional flag `VANTABE_ENABLED` to better control vantage status, keeping the previous leniencies
=> better vantage setup control

src/server/client.js, src/server/network-topology.js, src/server/server.js
- routes manager now also prints the argument names alongside the values
- client socket
=> improved client and server routes logging

src/server/bug-reporter.js, src/server/mailer.js
- could be improved to compress attachments
=> bug reporter big attachment handling fixes #2337

src/server/rpc/procedures/utils/api-consumer.js, src/server/rpc/procedures/utils/index.js, src/server/rpc/procedures/utils/service.js
this should help unify the services better. The base service class could be used to make up other types of services like those that consume CSV files
=> Refactored base service out of ApiConsumer

src/server/rpc/procedures/twitter/twitter.js
This is the Twitter change separated from #2334.
=> Refactor Twitter RPC

src/server/rpc/procedures/roboscape/roboscape.js, src/server/rpc/procedures/roboscape/robot.js
- created an onCommand handler to handle the user commands.
- Simplified the case statemetns
- removed some duplicate parts
- removed the `fields` parameter from `sendToClient`
=> roboscape refactor p2: oncommand fixes #2359

src/server/rpc/procedures/roboscape/roboscape.js, src/server/rpc/procedures/roboscape/robot.js
depends on https://github.com/NetsBlox/NetsBlox/pull/2360
- further reduces duplicated code on roboscape
- simplifies return values of `getRange` and `getTicks`
=> roboscape duplicated handlers improves #2361

src/server/rpc/advancedStorage.js
for consistency although it might be better for the default to be "netsblox"
=> changed advancestorage uri to admin

src/server/network-topology.js
extends Array class to keep the interface changes minimal.
=> client list

bin/build.js
https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/pull/781
=> ignore main.js when bundling client

src/server/logger.js
Adds DEBUG_DATE disable options discussed in #2387. Allows 'none', 'off', 'disable', or 'disabled' to turn off timestamp, and does default format if no setting.
=> Better option for disabling logger date Fix #2387

src/server/rpc/procedures/roboscape/firmware/melody.c, src/server/rpc/procedures/roboscape/firmware/melody.h
Removes Mario definition from Roboscape firmware.
=> Remove Mario from available melodies

src/server/rpc/procedures/roboscape/routes.js
- fixes a sanitization issue
- updates `setUserAccess` to only updates the users' portion of the robot document
=> roboscape route: request body sanitization, setUserAccess optimization

src/server/rpc/procedures/roboscape/routes.js
adds the missing first argument (query) for the update method.
=> added the missing query to update request fixes #2412

package-lock.json, package.json, src/server/rpc/procedures/chart/chart.js, src/server/rpc/procedures/chart/node-gnuplot.js
#2418 and sort of a prereq for #2417.
The big change is allowing lists of numbers to be plotted as a line chart, filling in the x coordinates sequentially. Need to figure out if this creates any new error cases.
=> Ease of use improvements for Chart RPC WIP #2418

src/server/rpc/rpc-manager.js, src/server/server.js
I am not sure if removing the logging when loading routes is a good idea but I suspect it is seldom used.
=> Combine init service logs. Removed excessive route logging. Closes #2249

src/server/rpc/procedures/paleo-climate/paleo-climate.js
Also, added a warning if there is an ice core w/o data and changed
the log about loading data into the database to `info`. Warnings
should be about things that are bad and not expected (at least
expected on the first run).
=> Ensure metadata exists for each ice core. Fixes #2467

src/server/rpc/procedures/paleo-climate/paleo-climate.js
=> Add "Date Range" to PaleoClimate.getAvailableDate. Closes #2469

src/server/rpc/rpc-manager.js, src/server/rpc/storage.js, src/server/storage/generic-storage.js
This also includes a change to the collection containing community (user-defined) services.
=> Add createCollection to RPC storage. Closes #2502

src/server/services/procedures/dev/dev.js
=> Add Dev.callerInfo RPC. Closes #2655

bin/netsblox, bin/netsblox-add-key.js, bin/netsblox-del-key.js, bin/netsblox-keys.js, src/common/constants.js, src/server/services/api-keys.js, src/server/services/api.js, src/server/services/index.js, src/server/services/procedures/utils/api-key.js, src/server/services/services-worker.js
This only supports API key creation via the command line. Still needs a web UI.
=> Add basic support for custom API keys. Closes #2526

src/server/services/procedures/air-quality/air-quality.js, src/server/services/procedures/google-maps/google-maps.js, src/server/services/procedures/movie-db/movie-db.js, src/server/services/procedures/nasa/nasa.js, src/server/services/procedures/paralleldots/paralleldots.js, src/server/services/procedures/traffic/traffic.js, src/server/services/procedures/utils/api-consumer.js, src/server/services/procedures/utils/api-key.js
This introduces a standard error (and generated message) for services with customizable API keys.
=> Update services to use InvalidKeyError. Closes #2667

src/server/services/api-keys.js, src/server/services/api.js, src/server/services/index.js, test/unit/server/services/api-keys.js
=> Add REST API for managing custom API keys. Closes #2670

src/server/services/procedures/key-value-store/key-value-store.js, test/unit/server/services/procedures/key-value-store.spec.js
This only adds passwords to individual keys (not to an entire subtree of keys).
=> Add optional password to KeyValueStorage get/put/child. Closes #2002

src/server/services/procedures/chart/color.js, src/server/services/procedures/chart/node-gnuplot.js
This PR contains a refactor of the code to move info from comments (which can be easy to forget to update when changing the code) to be evident from the code itself.
=> Refactored code for legibility wrt colors.

test/unit/server/storage/projects.js
Depends on https://github.com/NetsBlox/NetsBlox/pull/2761
=> Refactor project tests to async/await

src/server/services/procedures/berkeleyearth/berkeleyearth.js, src/server/services/procedures/historical-temperature/historical-temperature.js, test/unit/server/services/procedures/historical-temperature.spec.js
=> Berkeley Earth Historical Temperature RPC

src/server/services/procedures/historical-temperature/historical-temperature.js
=> Make returned data unique by date

src/server/services/procedures/new-york-public-library/new-york-public-library.js, src/server/services/procedures/smithsonian/smithsonian.js, src/server/services/procedures/utils/api-key.js, test/unit/server/services/procedures/new-york-public-library.spec.js, test/unit/server/services/procedures/smithsonian.spec.js
This is Devin Jean; pardon the github username, I can't really change it at this point without breaking a lot of references.
This pull request currently includes a functioning Smithsonian API service, but doesn't yet have the public interface test - I'll be adding that soon, but this is the important part.
=> added Smithsonian API service

src/server/services/procedures/human-mortality-database/human-mortality-database.js, src/server/services/procedures/mortality/mortality.js, test/unit/server/services/procedures/human-mortality-database.spec.js
Added a service to access the [Human Mortality Database](https://www.mortality.org/). Their data is arranged in a CSV file available for direct download from their website. I've written this service to use a meyers singleton pattern so that we automatically download and parse the file once per server startup, *but only upon request (use of the service)*. Thus, we have automatically updating data with no overhead if not being used (e.g. if we have to do a lot of server restarts to fix something unrelated).
=> added human mortality database service

src/server/services/procedures/iotscape/iotscape-services.js
=> Fix IoTScape timeouts

src/server/services/procedures/roboscape/ciphers.js, src/server/services/procedures/roboscape/speck.js
=> Replace symlink in RoboScape with path

src/server/services/procedures/autograders/autograders.js, src/server/services/procedures/autograders/integrations.js, src/server/services/procedures/autograders/routes.js, src/server/services/procedures/autograders/template.ejs, test/unit/server/services/procedures/autograders/autograders.spec.js, test/unit/server/services/procedures/autograders/integrations.spec.js
This is currently blocked by https://github.com/coursera/programming-assignments-demo/issues/35
=> Add coursera integration for autograding. Closes #2933

src/server/services/procedures/phone-iot/phone-iot.js
This PR changes the "device" argument to be a custom type (`Device`) which uses the BoundedString type and then ensures the device exists for the given device ID.
=> Add Device type in PhoneIoT service. Closes #3075

src/server/services/input-types.js, src/server/services/procedures/air-quality/air-quality.js, src/server/services/procedures/battleship/battleship.js, src/server/services/procedures/connect-n/connect-n.js, src/server/services/procedures/eclipse-2017/eclipse-2017.js, src/server/services/procedures/google-maps/google-maps.js, src/server/services/procedures/hangman/hangman.js, src/server/services/procedures/n-player/n-player.js, src/server/services/procedures/simple-hangman/simple-hangman.js, src/server/services/procedures/twitter/twitter.js, src/server/services/procedures/water-watch/water-watch.js, test/unit/server/services/input-types.spec.js
This PR adds new types: `Integer` and `BoundedInteger` that are just thin wrappers around `Number` and `BoundedNumber`, plus an is integer check. I also swapped over some existing instances of `Number` and `BoundedNumber` for int versions where it seemed appropriate.
=> integer types

package-lock.json, package.json, src/server/services/procedures/genius/data-prep.js, src/server/services/procedures/genius/genius.js, src/server/services/procedures/utils/api-key.js, test/unit/server/services/procedures/genius.spec.js
This adds the genius API to netsblox. Should we call it Genius or make it obvious that it is referring to lyrics/music?
=> Add Genius API for music lyrics. Closes #3283

src/server/services/procedures/nexrad-radar/nexrad-radar.js
Performance updates for the new NexradRadar service #3338. Latest commit gets another ~20% speedup.
Here's a flamegraph of testing the latest version: [flamegraph.html.zip](https://github.com/NetsBlox/NetsBlox/files/7873971/flamegraph.html.zip). Looks like the majority of the work is in the `Level2Radar` constructor call now.
@KurtXiao do you have any ideas? The issue is that NetsBlox has a 65 sec timeout for if an rpc takes too long (they're typically pretty fast). The service is currently up on [dev](https://dev.netsblox.org/?#) (called `NexradRadar`), but I had to bump up the timeout (just on dev) to 5min because, depending on the inputs, it takes too long. Since the majority of runtime seems to be in the parsing library, that's not your fault, but any improvements/ideas would be …
=> NexradRadar perf

src/server/services/procedures/word-guess/word-guess.js, test/unit/server/services/procedures/word-guess.spec.js
@gsteinLTU - I added the failing test for #3360. Could you take care of this?
=> Improve WordGuess feedback method

src/server/services/procedures/daily-word-guess/daily-word-guess.js, src/server/services/procedures/daily-word-guess/storage.js, src/server/services/procedures/word-guess/word-guess.js, test/unit/server/services/procedures/daily-word-guess.spec.js
=> Daily version of WordGuess service

src/server/services/procedures/roboscape/robot.js
=> Add "turn wheels" as alias of drive command

src/server/services/procedures/iotscape/iotscape.js
Allows IoTScape on editor
Close #3426
=> Remove alpha tag from IoTScape

_typos.toml
@brollb Adds a typos ignore rule for #3422.
=> Alpha Vantage Typos

src/server/services/input-types.js
=> Better description of `Object` type in docs

package.json, src/server/services/blocks2js.js
=> bump to snap2js 1.7.0

src/server/services/procedures/rain-viewer/rain-viewer.js
@brollb This has been around for a while and I have some demo projects that use it (but are dev-only at the moment).
=> stabilize RainViewer

src/server/services/procedures/nexrad-radar/nexrad-radar.js
=> Remove NexradRadar from editor

src/server/services/procedures/phone-iot/common.js, src/server/services/procedures/phone-iot/device.js, src/server/services/procedures/phone-iot/phone-iot.js, test/unit/server/services/procedures/phone-iot.spec.js
Adds support for new PhoneIoT sensors.
=> PhoneIoT New Sensors

docker-compose.yml
Close #3474 
@brollb Should I edit the readme to include this or are we saving that for when we do all the documentation?
=> Add commented-out development binds to docker-compose.yml
