src/client/blocks.js
This issue occurs because the context of the InputSlotMorph is different when creating a custom block as seen [here](http://i.imgbox.com/JtxNfXkk.png). 
More specifically, when in the custom block creation window, there is no accessible NetsBloxMorph parent.
Additionally, this also fixes the related issue of the the target role being reset when the custom block is created.
=> Restored role dropdown functionality in custom blocks. Fixes #427

src/client/messages.js
This commit fixes the layout issues that occur when resizing the `MessageCreatorMorph` window.
As was suspected, the issue was due to the parent (`MessageCreatorMorph`) not being updated. 
The dialog window must be resized correctly before applying/updating any children layouts.
=> Fixed message creating artifacts upon resizing. Fixes #222

src/client/cloud.js, src/client/room.js, src/server/rooms/NetsBloxSocket.js
This commit forces the room name to change on a user login if the room name is still the default name. 
As a result, users are now _unable_ to save a room as "MyRoom" when logged in (it will rename it before saving).
=> Room name changes on login if still default. Fixes #389

src/client/message-listeners.js
With this change, the message hat block is forced to process _all_ SlotMorphs from the context of the parent when updated (specifically, `ReadOnlyTemplateSlotMorphs`, the morphs responsible for the field displays).
This fixes the duplication bug because, previously, `MessageOutputSlotMorphs` would modify the fields from its own context, which meant that in some circumstances like duplication, it wouldn't remove all of its fields.
=> Forced message hat block to process all SlotMorphs when updated. Fixes #449

src/client/blocks.js, src/client/websockets.js, src/server/rooms/ActiveRoom.js, src/server/rooms/NetsBloxSocket.js
This commit clarifies and updates the available role destinations for the room.
Instead of `everyone` signifying all the roles in the room _except_ for yourself, there are:
* `others in room`, taking the place of the old `everyone` and signifying all the roles in the room _except_ for yourself, and
* `everyone in room`, signifying _all_ the roles in the room, _including_ yourself
This provides convenience and functionality for the user because oftentimes there is a need for everyone in the room, including the current role, to react to a message that a role sends. Without this, the user would need to use the `broadcast` blocks, which would clutter up the screen and add unnecessary complexity to the project.
=> Updated role destinations for room.

src/client/objects.js, src/client/room.js, src/client/websockets.js, src/server/rooms/NetsBloxSocket.js
This commit draws a message type palette to the left of the room for users to drag-and-drop message types to share among other roles in the room.
* Displays a fixed message palette built with a scroll frame to the left of the room graphic
* Dynamic updates (whenever you make/delete/receive a message type, it refreshes)
* NOTE: the current way of 'refreshing' the palette involves simulating a click of the 'room tab'. There should probably be a better way...however, without refreshing the palette, the focus on the room tab will be messed up on update of the palette (shifts to bottom right)
* **Drag and drop a message type from the palette to a role to share it**
* **Right click a message type from the palette to send it with a pop up dialog**
* **Left click a message type from the palette …
=> Added sharing of message types. Fixes #271

src/client/threads.js
This is a temporary fix for managing collaborative editing in a networked env
=> Removed message sending when collab (non-leader). Fixes #870

src/client/netsblox.js
This enables projects to be linked to using the syntax: `?action=private&ProjectName=SomeProjectName`. If the user is logged in (using a cookie) he/she will be able to open the project automatically.
These projects do not open in "app mode" as they are not published and it is assumed they are being worked on
=> Added support for private project links. Fixes #937

src/server/rpc/procedures/utils/api-consumer.js
let the caller of apiConsumer methods get access to the event object in case of errors
=> return the error event and log better Fixes #1300

src/server/rpc/procedures/eclipse-2017/eclipse-2017.js
When using the tempHistory and conditionHistory methods we get the latest database records based on based on requestTime only. We changed the behaviour from sorting by readAt to requestTime relying on the face that the most recent request will have the most recent sensor value to keep reporting the result of our latests requests.
Sorting first by the time the sensor was read and then our requestTime should solve this issue.
=> exclude outliers on *history methods for eclipse rpc Fixes #1411

test/client/actions.spec.js, test/client/index.html, test/client/snap-driver.js
I am not sure how this can get called with an undefined color but I know it can happen... maybe on undo?
Regardless, this fix makes sure it doesn't throw an exception and falls back on black. *Note*: the fix is actually in snap-undo but this adds a test and updates the submodule
=> Added default (black) for setColorField. Fixes #1481

src/server/rpc/procedures/twitter/twitter.js
The response for a  user with no tweets is fixed to be an empty array.
recentTweets is misbehaving as in if the requested user doesn't exist, it returns an empty array where instead it should send an error.
=> return empty array if the user has no tweets Fixes 1576

package.json, src/server/rpc/jsdoc-extractor.js, src/server/rpc/procedures/geolocation/geolocation.js, src/server/rpc/rpc-manager.js, test/server/rpc/jsdoc-extractor.spec.js
- scans services source codes for jsdoc blocks
- parses jsdocs
- finds the associated RPC with the parsed jsdoc
- provides this meta data to the rpc-manager
- + when building the RPCs, grabs the argument names from jsdoc if available
=> parse services for jsdoc and present rpc-manger with the metadata Fixes #1605

src/server/rpc/jsdoc-extractor.js, test/server/rpc/jsdoc-extractor.spec.js
the RPC manager mutated the doc object in the process of creating an endpoint for frontend services.
=> missing docs Fixes #1623

src/client/netsblox.js
Cloud data is structured slightly differently than the local project data. When loading a room, it was creating the data for the current role incorrectly (cloud data looked like local data). All it needed was to be nested in `<snapdata>` tags to make sure it was parsed as cloud data and not regular `<project>` xml.
=> xml for the role should be in cloud format. Fixes #1631

test/server/rpc/procedures/utils/api-consumer.spec.js
confirming that rejected promises are not being cached by adding tests
=> cache validity tests Fixes #1137

src/client/blocks-ext.js
This should make cases like #822 easier to understand for the end user as it will now give a meaningful error message.
=> Added better error msg for callRPC block w/ bad service. Fixes #822

src/client/actions.js, src/client/room.js, src/client/websockets.js, src/server/rooms/active-room.js, src/server/rooms/netsblox-socket.js, src/server/server-utils.js, test/server/server-utils.js
This PR moves the acceptance of actions to the server. The last action/commit id is stored in memory and is used to accept/reject any actions that are not made on the most recent version of the project.
The retrieval of the action id is performed async to make any changes to the storage location of the latest action ids easy to modify (important for supporting horizontal scaling or migrating it to a persistent location in the future).
=> Moved action acceptance to the server during collab. Fixes #1230

src/client/netsblox.js
I don't really like this approach but it fixes the bug. However, as this approach allows us to reuse the same functionality as when cloud projects are opened in general, I think this may be the best approach. Ideally, the `ProjectDialogMorph.prototype.rawOpenCloudProject` function would be on `IDE_Morph`. Regardless, reusing this functionality is ideal as it should be the least error prone.
=> Reuse the project dialog morph for opening projects by url. Fixes #1808

test/unit/server/storage/projects.js
most of our mocha tests are being ignored because of a leftover .only statement.
=> removed leftover .only

src/server/bug-reporter.js
I added the request headers from the original upgrade request (part of the ws spec) so the platform of the given user can be determined on a corrupt websocket message.
=> Added headers from upgrade req to bug report. Fixes #1948

src/server/rooms/netsblox-socket.js
Updated the `checkAlive` function to terminate the connection if the socket is not open.
=> Declare the socket dead if ws not open. Fixes #1951

src/server/rooms/netsblox-socket.js
This PR supports client detection of broken websocket connections (https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/pull/552). Ping messages are only sent if there has not been recent socket activity.
=> Moved ping-pong msgs to user-layer. Fixes #1999

src/server/rpc/procedures/cloud-variables/cloud-variables.js, test/assets/utils.js, test/unit/server/rpc/procedures/cloud-variables.spec.js
This pull request adds support for cloud variables in NetsBlox (similar to the existing KeyValueStore). There are two types of variables: public (default) and user (inspired by https://github.com/LLK/scratch-flash/issues/689). 
Public cloud variables can be shared between any two projects. This includes getting, setting, and deleting. Variables can be protected by providing a "password" argument to the service. This will result in the variable being password-protected (reads, writes, and deletion).
User cloud variables are stored for the given user (as the name suggests). 
In our deployment, all variables are subject to deletion after 30 days of inactivity (this is included in the service description).
=> Added CloudVariables Service. Closes #1542

src/server/rpc/procedures/google-maps/google-maps.js, test/unit/server/rpc/procedures/google-maps.spec.js
support for limiting cache buster precision. 
sets the precision limit to 7 meaning lat or lon of `ab.1234567WX == ab.1234567YZ`
=> googlemaps cache precision fixes #2036

src/server/rpc/procedures/google-maps/google-maps.js
limited google maps valid zoom range to 1,23
https://developers.google.com/maps/documentation/maps-static/intro
=> enforce google maps valid zoom range fixes #2089

.eslintrc.yml
updates Eslint to support es8 syntax. We still should keep the shared code with snap (client-side) code restricted to es5
=> linting support for Ecmascript 2017 Fixes #2174

src/server/rpc/procedures/utils/api-consumer.js, src/server/rpc/procedures/water-watch/water-watch.js
right now waterwatche's stop RPC returns null therefore the HTTP request to its corresponding endpoint hangs. This PR changes the RPC to return a promise which is then handled by RPC manager.
=> Waterwatch's stop RPC replies with a promise Fixes #2184

src/server/rpc/procedures/roboscape/roboscape.js
since many of the RPCs in this service return false if they fail it might be good to also return false in this case too. We could on other hand return a message or maybe utilize the error block?!
=> disallow easy robot id matching #2190

src/server/rpc/procedures/iex-trading/iex-trading.js
All stock symbol inputs are now converted to uppercase before being passed into the API. This will make both upper/lower/mixed case versions share the same cache (since they're the same stock). It's "officially" uppercase as that's the say stock symbols are typically presented, even though the API is not case-sensitive in its input (but does always output uppercase ticker symbols in the company information).
=> IEX Stock symbols are now uppercase internally Fixes #2209

package-lock.json, package.json, test/features/routes/groups.spec.js, test/utils/auth.js, test/utils/sha512.js
- adds clientside authenticator library keeping it as close to the browser env as possible using `xmlhttprequest` package
- modifies sha512 to be importable in node
- sets up the directory for route tests
required by #1699
=> prepration for routes tests fixes #2229

src/server/rpc/procedures/roboscape/roboscape.js
- renamed `content` to avoid name collision and losing function argument
=> fixed var name collision bug fixes #2250

src/server/rpc/procedures/utils/index.js, test/unit/server/rpc/procedures/utils/index.js
through a series of pull requests, this has become an issue mainly with table display form of the charting service's default options. More info available in the attached issue
=> snapstructure disable filtering of falsy values in arrays Fixes #2258

src/server/rpc/procedures/utils/api-consumer.js
Needs testing to make sure nothing is broken, but this is the fix from #2260 put directly into ApiConsumer instead of only the Translation service.
=> Change how ApiConsumer determines cache keys

src/server/rpc/procedures/azure-translation/azure-translation.js
This improves the caching for the Translation service. Now the cache properly uses the text data to distinguish between requests without needing the GUID to be in the URL.
@hamidzr How long are you thinking it should be held in cache?
=> Added custom cache key for Translation RPC and increased cache time Fix #2256 

src/server/logger.js
only send `warn` and `error` log levels to stderr.
=> support for changing debug's output stream on a per level basis

src/server/client.js
currently, it uses `this.uuid` which cannot be set at that point. might be able to get the clientId through some other way
=> use client counter for client logger name  Fixes #2281

src/server/rpc/procedures/nasa/nasa.js
refactored NASA service to use promises to utilize existing error handling. if the mars service provider doesn't come back online soon we might have to find a substitute or remove that part of the service.
also adds a new rpc: `apodDetails`
=> updated Nasa service Fixes #2301

bin/test-client.sh, package-lock.json, package.json, test/fixtures/users.js
allows running of the client tests without manually opening the browser.
since most of these tests depend on the server being up this repo looks like a good place for it.
Although I used JSON.stringify to stringify the command it is still an invalid string and can't be used directly in package.json.. why?
`{"test-client":"npx mocha-chrome http://localhost:8080/test --chrome-flags \'[\\"--no-sandbox\\"]\'"}`
using `mocha-chrome`
=> run the client tests through cli fixes #2307

bin/test-client.sh
the test script reads the port from the env variables and defaults to 8080
=> client-test port number read from env variable

test/assets/mock-rpc.js, test/assets/utils.js, test/unit/server/rpc/jsdoc-extractor.spec.js
fixes `undefined interface` logs
=> renamed leftover rpcName from #1368

src/server/rpc/rpc-manager.js
the logic of detecting intentional vs unintentional could use some work
// less descriptive logs and send the error message to the user
// more verbose logs. hide the error message from user (generic error)
- avoids leaking error information to the end users
- no scary error messages for the end user
- provides better error logs for important (unintentional) unhandled service exceptions
=> intentional vs unintentional rpc exception handling fixes #2350

src/server/rpc/procedures/roboscape/ciphers.js, src/server/rpc/procedures/roboscape/roboscape.js, src/server/rpc/procedures/roboscape/robot.js
refactored robots to support multiple ciphers.
keeps the default cipher as caesar cipher with [0] key
adds a new command to set the cipher: `set encryption CIPHERNAME keys`
- deprecates `set key ..`
=> roboscape: extendable cipher fixes #2394

.gitmodules, src/server/rpc/procedures/roboscape/ciphers.js, src/server/rpc/procedures/roboscape/robot.js, src/server/rpc/procedures/roboscape/speck.js
=> roboscape: speck cipher support fixes: #2396

src/server/rpc/procedures/roboscape/roboscape.js
fixes a bad conditional that fails to catch undefined robot object
=> roboscape return false when robot is not found fixes #2410

src/server/rpc/procedures/roboscape/firmware/roboscape.c
This just asks the module for its current connection status at bootup, if it's not configured (which would only be the case at bootup if the module was never configured or had an incomplete provisioning), it defaults to the usual network for camps.
=> If robot wifi module is not setup, give it a default AP

src/server/rpc/procedures/paleo-climate/data/antarctic-co2-composite/index.js
The data ingestion was filtering out the data with a negative date. Since the date is reported in yearsBP, this omitted data after 1950.
=> Fix regex for data lines in Antarctic Composite CO2 data. Fixes #2484

src/server/rpc/rpc-manager.js
This PR removes logging for user errors ("intentional errors") which were previously logged as warnings. This also reverts the addition of "something went wrong" which I find rather frustrating...
=> Removed opaque error msgs and logs for user errors. Closes #2483

src/server/rpc/procedures/air-quality/air-quality.js, src/server/rpc/procedures/british-museum/british-museum.js, src/server/rpc/procedures/google-streetview/google-streetview.js, src/server/rpc/procedures/iex-trading/iex-trading.js, src/server/rpc/procedures/met-museum/met-museum.js, src/server/rpc/procedures/movie-db/movie-db.js, src/server/rpc/procedures/paralleldots/paralleldots.js, src/server/rpc/procedures/pixabay/pixabay.js, src/server/rpc/procedures/thing-speak/thing-speak.js, src/server/rpc/procedures/translation/translation.js, src/server/rpc/procedures/trivia/trivia.js, src/server/rpc/procedures/twitter/twitter.js, src/server/rpc/procedures/utils/api-consumer.js, src/server/rpc/procedures/water-watch/water-watch.js, src/server/rpc/procedures/weather/weather.js, test/unit/server/rpc/procedures/utils/api-consumer.spec.js
This updates API consumer to actually treat query strings like query strings and adds `path`, `url` options.
=> Add "path", "url" options for requests in API consumer. Closes #2571

src/server/rpc/procedures/iex-trading/iex-trading.js
This PR removes the IEXTrading service. Usage of old callRPC blocks using the service will result in the following error:
=> Deprecate IEXTrading. Closes #2486

src/server/services/procedures/air-quality/air-quality.js, src/server/services/procedures/geolocation/geolocation.js, src/server/services/procedures/google-maps/google-maps.js, src/server/services/procedures/google-streetview/google-streetview.js, src/server/services/procedures/movie-db/movie-db.js, src/server/services/procedures/nasa/nasa.js, src/server/services/procedures/paralleldots/paralleldots.js, src/server/services/procedures/pixabay/pixabay.js, src/server/services/procedures/traffic/traffic.js, src/server/services/procedures/translation/translation.js, src/server/services/procedures/twitter/twitter.js, src/server/services/procedures/utils/api-consumer.js, src/server/services/procedures/utils/api-key.js, src/server/services/procedures/utils/index.js, src/server/services/procedures/weather/weather.js
This updates the use of API keys in the services to be able to be overridden. This also standardizes some of the error messages for unsupported services (by using the helper method `setRequiredApiKey`) and highlights some of the inconsistencies with the environment variable naming for API keys.
Also, this updates the Google geocoding API to use the same key as GoogleMaps and GoogleStreetView.
=> Update services to support custom API keys. Closes #2661

src/server/services/procedures/service-creation/blocks/getColumns.tpl, src/server/services/procedures/service-creation/blocks/getTable.tpl, src/server/services/procedures/service-creation/blocks/getValue.tpl, src/server/services/procedures/service-creation/service-creation.js, test/unit/server/services/procedures/service-creation.spec.js
This adds the RPCs as described in #2648 with the exception that getting an entire column has "Column" as part of the RPC name. Otherwise, it is exactly as described in the issue.
It is worth noting that these default options are only the case when the first column is a unique identifier for the given row. There could still be some improvements to be made to the defaults when the first column is not unique...
=> Update data service defaults. Closes #2648

package-lock.json, package.json, src/server/services/procedures/base-x/base-x.js, test/unit/server/services/procedures/base-x.spec.js
This PR adds a simple BaseX service which provides access to a BaseX instance via the `query` and `command` operations (via the [REST API](http://docs.basex.org/wiki/REST)). 
It could be useful to add support for the `commands` operation which would enable users to run entire [command scripts](http://docs.basex.org/wiki/Commands#Command_Scripts) though this is not included in this PR.
=> Add BaseX service. Closes #2697

src/server/services/procedures/covid-19/covid-19.js
This removes the @alpha tag from the COVID-19 service making it ready for deployment!
=> Official release of COVID-19 service

src/server/services/procedures/new-york-public-library/new-york-public-library.js, src/server/services/procedures/smithsonian/smithsonian.js
Addresses #2869. I couldn't find anywhere that the categories were defined, so I just assumed them to be strings. I gave both Smithsonian and NYPL the `History` category, as nothing pre-existing seemed to match. I think the simple term `History` matches the target audience verbage, but if it's too general (e.g. stock data could also be considered historical), we could do something like `Museum`/`MuseumData`/`MuseumContent`.
=> added @alpha to Smithsonian and NYPL Services

src/server/services/procedures/ocean-data/ocean-data.js
Akos mentioned it would be nice to have optional start/end year params for the OceanData service. This PR adds them as numeric params which default to -inf/+inf and denote inclusive bounds. Thus, default values function identically to previous behavior. If `startYear > endYear`, empty list is returned.
=> OceanData service: added optional start/end year params

src/server/services/procedures/new-york-public-library/new-york-public-library.js
Apparently, sometimes the json returned from the NYPL `getDetails` API call will split some of their fields into disjoint objects. This PR fixes this by checking if it's split (instance of array) and doing a shallow search for the desired field. Other than that, it seems to work as-is, but I additionally added some more checks which never came up in testing but couldn't hurt to have.
=> NYPL getDetails bugfix

src/server/services/procedures/this-x-does-not-exist/this-x-does-not-exist.js, test/unit/server/services/procedures/this-x-does-not-exist.spec.js
I thought it would be neat for (esp.) games to be able to fetch random profile images, so I made an RPC for accessing images from [thispersondoesnotexist.com](thispersondoesnotexist.com). From there I found out about a bunch of other related sites, so I made RPCs for all the ones I could find. All the images sources claim to be safe (not inappropriate) and I did extensive testing on each of them (randomly) and found nothing bad. I put the service under the `Science` category for now due to being directly related to GANs.
=> added this-x-does-not-exist procedure

src/server/api/core/auth.js, src/server/api/core/errors.js, src/server/api/core/projects.js, test/unit/server/api/core/projects.js
This PR adds support for fetching the latest version of a role via the REST API. Note that this includes unsaved edits as these are the key issue in #2923. That said, the remainder of the fix will be implemented on the client; this provides backend support for prompting the user to reload with the latest (even unsaved) version of the project. Essentially, this will fetch the latest version of the given role and then load it.
=> Add exportRole to REST API. Closes #2923

src/server/storage/blob/blob.js, src/server/storage/blob/fs.js, test/unit/server/services/procedures/connectn.spec.js
This reduces the somewhat excessive logs when saving data to the blob, removes unneeded globals (for the linter), and removes Q in favor of async/await.
=> Minor code cleanup

src/server/services/procedures/chart/chart.js, test/unit/server/services/procedures/chart/chart.spec.js
This PR ensures that implicit x values are 1-indexed (like NetsBlox). It also includes some refactoring to ensure the changes are easily testable.
=> Implicit x-values are 1-indexed in Chart.draw. Closes #3017

src/server/services/procedures/chart/chart.js
This adds a behavior to the chart line parser that allows 2xN (N >= 3) to be automatically transposed into the accepted Nx2 form (which is really just zipping). There's currently code that allows only one line to be passed, and logic to allow drawing lines with only y values. So the only issue I see so far is that passing `[x,y]` would be ambiguous between `[[x, y]]` (one transposed line) and `[[x], [y]]` (two lines with only y values).
Also I cleaned up some of the error handling code: unnecessary try-catch on internal functions, throwing strings instead of `Error`, and directly manipulating the response object to set errors.
=> chart 2xN transposing and error cleanup

src/server/services/procedures/iotscape/routes.js, src/server/services/procedures/phone-iot/routes.js, src/server/services/procedures/roboscape/routes.js
Closes #3022
Adds `api/services/iotscape/port`, `api/roboscape/port`, and `api/services/phone-iot/port` endpoints. They either provide the port or respond that it is not enabled (Should the endpoints return a different status code for that case?).
=> Add port endpoints for services

src/server/services/jsdoc-extractor.js, src/server/services/procedures/dev/dev.js, test/unit/server/services/jsdoc-extractor.spec.js
This PR adds support for specifying a set of categories for RPCs and should be useful for PhoneIoT (as well as others). Categories are optional but can be specified with:
```javascript
/**
* Add a custom image display to the device, which is initially empty.
* This can be used to display an image, or to retrieve an image taken from the device's camera.
* If an event is provided, it will be raised every time the user stores a new image in it (params: 'id').
* Returns the id of the created control, which is used by other RPCs.
* @category Display
* @param {string} device name of the device (matches at the end)
* @param {BoundedNumber<0, 100>} x X position of the top left corner of the image display (percentage).
* @param {BoundedNumber<0, 100>} y Y position of the top left corner of the …
```
=> Add categories to RPC metadata. Closes #3033

src/server/services/jsdoc-extractor.js, src/server/services/procedures/dev/dev.js, test/unit/server/services/input-types.spec.js, test/unit/server/services/jsdoc-extractor.spec.js
This adds support for duck typing objects passed as arguments to RPCs. As an example:
```javascript
/**
* Call an argument with a duck typed options object
*
* @param{Object} options
* @param{String} options.name
* @param{Number} options.age
* @param{Number=} options.height
*/
```
=> Add duck typing for Objects. Closes #3070

src/server/services/input-types.js, test/unit/server/services/input-types.spec.js
This PR adds two features to the `Array` input type. First, it adds upper and lower bounds for length, like `BoundedString` does. This can be specified like `@param {Array<Any, 2, 5>}`. Second, it adds support for complex inner types. It looks like the parser for inner types always yields an object of form `{ name: String, params: Any[] }` for inner types having angled brackets, so I added a wrapper for working with those. So now you can do complex types like a list of 0/1 as `@param {Array<Enum<0,1>>}`. Or perhaps more useful, `@param {Array<BoundedNumber<0>>}` for a list of non-negative numbers.
=> added Array type bounds and complex inner types

src/server/services/input-types.js, test/unit/server/services/input-types.spec.js
Closes #3098. The duck typing I added to the chart service a few days ago had an unforeseen issue: the `defaultOptions` RPC is returning undefined values (which at some point are converted to null) for some fields that default to not being set, a reasonable use case. The issue is that these values fail to parse.
This PR attempts to fix the general problem by disregarding input values that are undefined/null. I also tried to clean up the parsing code a bit.
=> changed duck typing to ignore undefined/null

bin/prestart.js, src/server/docs/adv/rpc-support.rst, src/server/docs/index.rst, src/server/services/procedures/autograders/docs/index.rst, src/server/services/procedures/phone-iot/docs/Display.rst, src/server/services/procedures/phone-iot/docs/Sensors.rst, src/server/services/procedures/phone-iot/docs/Utility.rst, src/server/services/services-worker.js
Closes #3106. I swapped over from regex replace for doc templating to ejs, and added some extra info to the metadata. This includes an `apiKeys` object, which is used in a normal ejs template to automatically generate the API key docs for all services.
=> 3106 Automatically generate API key documentation for Services

bin/prestart.js, src/server/services/jsdoc-extractor.js, src/server/services/procedures/phone-iot/common.js, src/server/services/procedures/phone-iot/phone-iot.js, test/unit/server/services/jsdoc-extractor.spec.js
In PhoneIoT there were two RPCs I was supporting that I don't see any use for anymore (and might be confusing). One was `getRotation`, which returns a 4D vector and is therefore overcomplicated for students. The other was `getGameRotation`, which, while not identical to `getOrientation`, is basically the same thing (just a different reference frame). Orientation is better due to being absolute.
So I marked these RPCs as deprecated.
More interestingly, I noticed there wasn't a way to mark duck typing fields as deprecated, so I added that. This was needed to make the `rotation` and `gameRotation` fields on `listenToSensors` not show up in the docs. Now, any `@param {type} <name> <desc>` will have its description parsed for leading tags.
=> PhoneIoT RPC cleanup

src/server/services/procedures/roboscape/robot.js
Close #3124 
This PR quickly adds the ability to send a uint8 to a robot for display and modifies the HW key generation code to send these to robots (although physical robots can't respond to it yet).
It also includes a command to access it, which students could use e.g. to display output on the robot instead of only on the stage:
=> Add numeric display feature for simulated robots

src/server/services/procedures/autograders/autograders.js, src/server/services/procedures/autograders/docs/overview.rst
Down the road, it would probably be nice to have the documentation detect the server URL rather than hardcoding editor.netsblox.org but this works for now...
=> Remove autograder warning docs

src/server/services/procedures/phone-iot/common.js, src/server/services/procedures/phone-iot/device.js, src/server/services/procedures/phone-iot/phone-iot.js
PhoneIoT had some special sensor getters like `getCompassDirection` that didn't have data streaming equivalents (for `listenToSensors`). This PR just adds extra fields to the accelerometer and orientation sensor messages with those extra values.
=> PhoneIoT extended sensor update fields

src/server/services/procedures/roboscape/robot.js
@brollb This change is needed for tomorrow's camp. Would you be able to get a new version onto editor with this included?
The number key messages previously weren't being repeated like the LED blinks for the keys are. We were having issues with them not showing up reliably. 
Eventually we'll need a better fix for this, but there isn't time before the camp tomorrow. Repeating them like the LED messages already do seems to solve the problem for now.
=> Repeat number messages for RoboScape key

src/server/services/procedures/phone-iot/device.js
Removed some straggling radian to degree conversions that are now incorrect since the app now sends degrees directly. I didn't notice it before because it only affects the direct access RPCs like `getOrientation` and I've mostly been using the streaming methods.
=> PhoneIoT unit fix

bin/build-docs.js, bin/netsblox-start.js
Closes #3143. Switched over to using the services server for doc filtering. Not sure how to test it like the deployment would be, but it works on local and it targets the `SERVICES_URL` env var, so that's probably ok.
=> use services server for doc filtering

src/server/services/procedures/phone-iot/device.js, src/server/services/procedures/phone-iot/phone-iot.js
Added a feature to let PhoneIoT devices request to be forgotten (and then re-registered) in case there's ever an issue with the sending socket on the server side (a non-reproducible bug I ran into twice). Also, if we ever add encryption (already in there, but not used), this'll let the user reset the password manually.
=> PhoneIoT connection reset

src/server/services/procedures/thing-speak/thing-speak.js, test/unit/server/services/procedures/thingspeak.spec.js
The search functions for thingspeak seem to be the only parts that weren't working (details and feeds look good, though I didn't test private feeds). This PR fixes the search methods, which seemed to be returning an arbitrary number of results, some of which were empty. I rewrote the relevant functions in more modern async style to be more readable. I added a limit param for search by tag and location. This also happens to fix #1544.
=> thingspeak service fix

bin/build-docs.js
Closes #3186. Apparently Sphinx has no way to disable duplicate function definition warnings, so this PR just adds filtering so that the build script doesn't consider them to be errors.
=> ignore dupe fn warnings during doc build

src/server/server.js
Don't follow redirects when proxying requests to the services. This also removes one more usage of the deprecated `requests` module.
=> Don't follow redirects when proxying requests to the services. Fix #3193

src/server/services/input-types.js, src/server/services/procedures/phone-iot/phone-iot.js
Closes #3255. Apparently the issue was even simpler: the `SensorPeriod` parser was passing `baesParams` into `defineType()` instead of `baseParams`. I fixed that and added a check to `defineType()` that will make sure no unexpected fields like this are present in the future.
=> Sanitize extra `defineType` fields

src/server/services/procedures/fbi-crime-data/types.js
Closes #3262. Apparently their value for `Territories` should actually be `U.S. Territories`, so I just changed the mapped value.
=> 3262 JSON error from FBICrimeData

src/server/services/procedures/iotscape/iotscape-services.js, src/server/services/procedures/iotscape/iotscape.js
This moves the JSON parsing into a try block so the error cases can be handled more gracefully.
=> Handle malformed JSON in IoTScape better

src/server/services/input-types.js, src/server/services/procedures/hurricane-data/hurricane-data.js, src/server/services/procedures/ice-core-data/ice-core-data.js, src/server/services/procedures/iotscape/iotscape.js, src/server/services/procedures/new-york-times/new-york-times.js, src/server/services/procedures/phone-iot/phone-iot.js, src/server/services/procedures/roboscape/roboscape.js, src/server/services/procedures/water-watch/water-watch.js, src/server/services/services-worker.js, test/unit/server/services/input-types.spec.js
This PR adds a validation step to the service loader that guarantees RPC arg/ret types actually exist. For instance, we had several occurrences of `array` or `string` which wouldn't properly get parsed. For fs services, this will throw a hard error on startup, so we can't accidentally make these errors in the future. Non-fs services will log an error, but otherwise permit it.
The Roboscape service had rpcs that took `string` (unparsed) and internally wanted it to either be an array of strings or a single string. To handle this with proper typing, I introduced a new type to express this as `Union<Array<String>,String>` (which displays in the docs as `AnyOf` rather than `Union`). It takes one or more types and returns the first successful parse, or an error stating why every option failed. …
=> Static RPC Type Sanitizing

src/server/services/procedures/covid-19/types.js, src/server/services/procedures/covid-19/vaccination/vaccination-data-source.js, test/unit/server/services/procedures/covid-19/vax-data.spec.js
Closes #3291. The vaccination categories RPC not working was simply due to a missing export (kinda surprised node didn't complain about that directly).
The vaccination data RPC was returning empty list for everything. Turns out that's because the datasource it was dynamically fetching at runtime changed their csv file structure. I've hardened the parser against future changes by restructuring each row as an object based on the header fields.
There's still the issue that came up in the meeting about needing to fetch all the data just to get the country list, but since it's all in a single CSV file (which we cache), there's not much we can do about it (assuming at least one call to actually fetch data is made). Also the file itself is only 4MB (currently). I couldn't reproduce the crash …
=> 3291 Fix Vaccination RPCs

src/server/services/input-types.js, src/server/services/procedures/geolocation/geolocation.js, src/server/services/procedures/utils/api-key.js, test/unit/server/services/input-types.spec.js, test/unit/server/services/procedures/geolocation.spec.js
Closes #3323. This adds RPCs `timezone` and `streetAddress` to `Geolocation`. `timezone` takes as input either a list of `[lat,long]` or a string to lookup through `geolocate`. To facilitate this, I also added an input type called `Tuple`. `streetAddress` takes an address string and pipes it through `geolocate` to get the formatted address, which was conveniently already available after a tiny refactor.
Note: a new api key is needed just for the `timezone` RPC, but it looks like the required key machinery we have set up atm doesn't allow multiple keys.
=> geoloc timezone #3323

src/server/services/procedures/phone-iot/common.js, src/server/services/procedures/phone-iot/device.js
@brollb Fixes a PhoneIoT bug where images that are too big to fit in a UDP packet were causing "Internal Server Error" and not working. This changes the img prep logic to do auto resizing. Unfortunately, it's hard to predict size after jpeg compression, so it's attempted in a loop until it fits in the right size, but default should work first-try for most inputs.
=> Phoneiot img fix

bin/build-docs.js
Closes #3307. Adds doc links for inner types. RST doesn't allow links inside of (inline) code literals, and we can't (easily) switch to raw html since RST requires a double new line to start a protocol block and most of these links are inside of bullet points (new lines would break them). Instead, this adds a parenthesized list of named type links after the code-formatted block.
Example: 
Filtering is performed so that non-types like in `BoundedNumber<0, 10>` don't get linked. Also, the links appear in the same order as in the type declaration, but are deduped.
=> Doc links for inner types #3307

src/server/services/procedures/thing-speak/thing-speak.js, test/unit/server/services/procedures/thingspeak.spec.js
ThingSpeak was including search results for stale entries that hadn't had new data in eons. This adds an additional optional param to the search functions called `updatedSince`, which is a cutoff `Date` used for filtering. I also refactored the search helper function to take an include predicate, so we don't have to do the grab-everything-and-filter approach that `searchByTagAndLocation` was using.
Since we have `updatedSince: Date`, users can specify the time unix-epoch-style like `time in millis` (the block) minus a user-defined constant. But I didn't want to forbid using an absolute time, which is why the input isn't just the window length.
Currently the default for `updatedSince` is not to filter, which preserves backwards compatibility. But maybe we want to consider some relative …
=> ThingSpeak `updatedSince` filtering

src/server/services/services-worker.js
Close #3358 
@brollb I'm not sure if this is the project ID you'd prefer it use (there's also one from the socket RemoteClient, although I think they should be the same), but the issue was that the `projectId` it was using was coming up undefined. After changing this it seems to correctly make separate service instances again.
=> Use defined project ID when setting up service instances

src/server/services/procedures/phone-iot/phone-iot.js
Minor updates to PhoneIoT docs, mostly relating to the `readonly` option for widgets.
=> PhoneIoT doc updates

src/server/services/input-types.js, test/unit/server/services/input-types.spec.js
Adds extended formats for date parsing, which are backwards compatible with the previous (builtin) format. Primarily, this adds the ability to use meta times like `now` or `today`, as well as apply time offsets like `now +10min`. These can also be applied to non-meta times (any format previously supported), like `2021/10/25 -2weeks` or `2019/6/22 -1min`. They can also chain like `today +7hr +22min +17s +82ms` and are whitespace invariant between tokens.
Also fixes a bug where passing a number like `2020` would previously parse as a unix timestamp, but passing the string `'2020'` would be Jan. 1, 2020. Not _really_ a bug, but Snap! is iffy about string vs number typing, so it seemed like something we wouldn't want.
The intent for this is use in the new `updatedSince` param for thingspeak …
=> Extended `Date` Parser

src/server/services/procedures/phone-iot/common.js, src/server/services/procedures/phone-iot/device.js, src/server/services/procedures/phone-iot/phone-iot.js, test/unit/server/services/procedures/phone-iot.spec.js
Updates PhoneIoT messages from widgets to also send the device ID, which is useful if one project connects to multiple devices (alternative was making unique ids for the same control on different devices, such as name mangling).
Also renames `bearing` values to `heading` (I had the terminology wrong originally), as well as `getBearing` to `getGPSHeading`. These changes are backwards compatible since both `heading` and `bearing` (deprecated) are sent in sensor updates, and `getBearing` is now a deprecated alias to `getGPSHeading`.
=> phoneiot msg update

src/server/services/input-types.js, src/server/services/procedures/cloud-variables/cloud-variables.js, test/unit/server/services/input-types.spec.js, test/unit/server/services/procedures/cloud-variables.spec.js
- Adds a few fused operations like `lockAndGet`, `setAndUnlock`, and `getAndSet` for both global and user variables.
- Adds the ability to asynchronously listen for updates to a variable (global or user) via message passing
- Only allowed after successful auth
- Updates stop when the variable is deleted (prevents bypassing a new password)
Updated the service impl to use `async`/`await` instead of `.then`/`.catch`.
Also fixes a bug where deleting an undefined variable was having a null reference error. Now this gives a nice error message. Since it lacked a test case, there's no current standard for this, so we could just as well make it a no-op (I'm fine either way).
---
These might become important soon, as PyBlox is using the `CloudVariables` service to emulate rooms by storing global …
=> Extended CloudVariables RPCs

src/server/server.js
@brollb Adds a global 403 filter to all routes that forbids any request with an `x-netsblox-source` header. This requires the corresponding [browser PR](https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/pull/1297) to actually block anything.
=> Forbid NetsBlox HTTP Reqs

src/server/services/jsdoc-extractor.js, src/server/services/procedures/shared-canvas/shared-canvas.js
Improves RST link markup cleaning. Links in RST take the form `` `label <target>`_ ``, or `` `label <target>`__ `` for anonymous links (preferred). The old cleanup logic was just taking the interior like `label <target>`, and only 1 underscore. The new cleanup logic takes both underscores and cleans it to `label (target)`.
=> Better Link Markup Cleaning

src/server/services/procedures/thing-speak/thing-speak.js
Changes Thingspeak RPCs to use meters for distance-based filtering. Previously the units were undocumented (both in NetsBlox and the Thingspeak API), but experimentation shows that it was actually expecting meters. This changes the RPCs to expect meters instead, which matches other services like GoogleMaps and Geolocation.
=> change Thingspeak to use meters

src/server/services/input-types.js, test/unit/server/services/input-types.spec.js
Fixes an edge case of parsing `Date` objects that was causing `today +1d` (today plus 1 day) to fail to parse because javascript accepts `today +1` as a valid builtin `Date` with Unix epoch timestamp `1`, and the rest of the string then fails to parse as an offset sequence.
=> fix Date parsing edge case

src/server/services/procedures/phone-iot/phone-iot.js, test/unit/server/services/procedures/phone-iot.spec.js
Quality of life changes for PhoneIoT. Adding widgets now automatically registers to receive events, and added a dedicated `stopSensors` RPC for discoverability (previous method was to explicitly listen to no sensors).
=> Phoneiot Update

src/server/services/procedures/human-mortality-database/human-mortality-database.js
The HumanMortalityDatabase had the audacity to move their CSV file download link. Fixed now.
=> fix csv file url

src/server/routes/middleware.js
Originally, this was written with the username, password in the body but then updated to allow logging in from the cookie (no credentials in the body). This meant that the username may be undefined when retrieved from the request body. If this was the case, I had updated the method to grab it from the cookie.
However, this exposes a pretty big security vulnerability if someone logs in with 1 account and sends a different username in the request body. The cookie will authenticate the user but then `username` will resolve to the incorrect value. (It should resolve to the value from the cookie rather than request body.)
=> Default username should be from cookie - not request body

src/server/services/procedures/autograders/template.ejs
Handle exceptions from the new `labelPart` code (used to return `null`).
=> Autograders Fix

docker-compose.yml
Saw these were uncommented in fcfaf12a14d66091369aae6c050f130de29873ac, this re-comments the dev lines, along with removing an API key that should not be there.
=> Revert uncommented lines in docker-compose

docker-compose.yml
Current docker-compose file does not allow using new/modified tests on browser, which makes it hard to develop new features.
=> Include option for local test directory in browser dev config
